export const aboutData = {
    title: 'Maktab Haqida',
    description:
        "Respublika ixtisoslashtirilgan dizayn maktabi haqida umumiy ma’lumot",
    school_datas: `Toshkentda rо‘y bergan 1966-yilgi zilzila vayronalarini tugatish va maxsus malakali mutaxassislar tayyorlash maqsadida Toshkent maxsus о‘rta texnik bilim yurti sifatida 1967-yil tashkil topgan. Uning sobiq talabalari Toshkent metrosi, muzeylar, ulkan inshootlar va uy-joylarni qurishda faol ishtirok etishgan. 1989-yilda Respublika о‘quv yurtlari orasida birinchi YUNESKOga a’zo bо‘ldi. 1984-yilda  me’mor va quruvchi Asadulla Ashrapovich Xо‘jayev nomi berildi. 1994-yilda О‘zbekiston Respublikasi xalq ta’limi vazirligi buyrug‘iga asosan, milliy hunarmandchilik litseyiga aylantirildi.
        О‘zbekiston Respublikasi Prezidentining “О‘zbekiston Badiiy Akademiyasini tashkil etish haqida”gi 1997-yil 23-yanvardagi Farmoni va О‘zbekiston Respublikasi Vazirlar Mahkamasining “О‘zbekiston Badiiy Akademiyasining faoliyatini tashkil etish tо‘g‘risida”gi 1997-yil 11-martdagi qaroriga asosan ta’lim muassasasi О‘zbekiston Badiiy Akademiyasi tasarrufidagi “A.A.Xо‘jayev nomidagi tasviriy va amaliy sanat bilim yurti” deb nomlandi. 2004-yil О‘zbekiston Respublikasi Badiiy Akademiyasi tasarrufidagi “A.A.Xо‘jayev nomidagi Respublika Dizayn kolleji” maqomi  berildi.Kollej maqomi va faoliyati о‘zgarishi bilan  binolarda ta’mirlash va qayta  ta’mirlash, о‘quv va ishlab chiqarish ta’lim ustaxonalarida yangi mutaxassisliklar bо‘yicha jihozlash ishlari о‘tkazildi.Xalq deputatlari Toshkent shahar Kengashining 2013-yil 9-apreldagi “Toshkent shahridagi ba’zi geografik obyektlar nomlarini tartibga keltirish tо‘g‘risida”gi 260/4-27-sonli qarori hamda Toshkent shahar О‘rta maxsus, kasb-hunar ta’limi boshqarmasining 2013-yil 19-iyuldagi 186-sonli buyrug‘iga binoan “A.A.Xо‘jayev nomidagi Respublika Dizayn kolleji”ga yangi “Respublika Dizayn kolleji” deb nom berildi. Kollej binosi 750 о‘ringa mо‘ljallangan bо‘lib, 5ta asosiy bino va 7ta yordamchi binolardan iborat.
        О‘zbekiston Respublikasi Vazirlar Mahlkamasining 2019-yil 9-yanvardagi “Ixtisoslashtirilgan san’at va madaniyat maktablari hamda maktab- internetlarining faoliyatini tashkil etish to’g’risida”gi 9 - sonli qarori hamda O’zbekiston Badiiy akademiyasining 2019 - yil 11 - yanvardagi I - 497 - sonli buyrug’iga asosan “Respublika Dizayn kolleji” “Respublika ixtisoslashtirilgan dizayn maktabi” deb yangi tahrirda nomlandi. `,
goals: [
    "O'quvchilarning intellektual rivojlanishini qo'llab-quvvatlash.",
    "Har bir o'quvchining potentsialini ochish.",
    'Innovatsion ta\'lim usullarini joriy etish.',
],
};